// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/home/data/repos_impl/home_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:fitness_app/features/home/data/datasources/contract/home_remote_data_source.dart'
    as _i6;
import 'package:fitness_app/features/home/data/models/daily_recommendation_exercise_dto.dart'
    as _i2;
import 'package:fitness_app/features/home/data/models/muscles_by_group_response.dart'
    as _i5;
import 'package:fitness_app/features/home/data/models/muscles_group_dto.dart'
    as _i4;
import 'package:fitness_app/features/home/data/models/recommendation_meals_dto.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDailyRecommendationExerciseDto_0 extends _i1.SmartFake
    implements _i2.DailyRecommendationExerciseDto {
  _FakeDailyRecommendationExerciseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeRecommendationMealsDto_1 extends _i1.SmartFake
    implements _i3.RecommendationMealsDto {
  _FakeRecommendationMealsDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMusclesGroupDto_2 extends _i1.SmartFake
    implements _i4.MusclesGroupDto {
  _FakeMusclesGroupDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMusclesByGroupResponse_3 extends _i1.SmartFake
    implements _i5.MusclesByGroupResponse {
  _FakeMusclesByGroupResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i6.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.DailyRecommendationExerciseDto> getDailyRecommendationExercise(
    int? limit,
    String? targetMuscleGroupId,
    String? difficultyLevelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyRecommendationExercise, [
              limit,
              targetMuscleGroupId,
              difficultyLevelId,
            ]),
            returnValue: _i7.Future<_i2.DailyRecommendationExerciseDto>.value(
              _FakeDailyRecommendationExerciseDto_0(
                this,
                Invocation.method(#getDailyRecommendationExercise, [
                  limit,
                  targetMuscleGroupId,
                  difficultyLevelId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i2.DailyRecommendationExerciseDto>);

  @override
  _i7.Future<_i3.RecommendationMealsDto> getFoodRecommendation() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodRecommendation, []),
            returnValue: _i7.Future<_i3.RecommendationMealsDto>.value(
              _FakeRecommendationMealsDto_1(
                this,
                Invocation.method(#getFoodRecommendation, []),
              ),
            ),
          )
          as _i7.Future<_i3.RecommendationMealsDto>);

  @override
  _i7.Future<_i4.MusclesGroupDto> getAllMuscles() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMuscles, []),
            returnValue: _i7.Future<_i4.MusclesGroupDto>.value(
              _FakeMusclesGroupDto_2(
                this,
                Invocation.method(#getAllMuscles, []),
              ),
            ),
          )
          as _i7.Future<_i4.MusclesGroupDto>);

  @override
  _i7.Future<_i5.MusclesByGroupResponse> getMusclesByGroup(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMusclesByGroup, [id]),
            returnValue: _i7.Future<_i5.MusclesByGroupResponse>.value(
              _FakeMusclesByGroupResponse_3(
                this,
                Invocation.method(#getMusclesByGroup, [id]),
              ),
            ),
          )
          as _i7.Future<_i5.MusclesByGroupResponse>);
}
