// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/home/domain/usecases/get_food_recommendation_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/api_layer/api_result/api_result.dart' as _i4;
import 'package:fitness_app/features/home/domain/entities/exercise_entity.dart'
    as _i5;
import 'package:fitness_app/features/home/domain/entities/meal_entity.dart'
    as _i7;
import 'package:fitness_app/features/home/domain/entities/muscle_entity.dart'
    as _i9;
import 'package:fitness_app/features/home/domain/entities/muscle_group_entity.dart'
    as _i8;
import 'package:fitness_app/features/home/domain/repositories/home_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepo extends _i1.Mock implements _i2.HomeRepo {
  MockHomeRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i5.ExerciseEntity>>>
  getDailyRecommendationExercise(
    int? limit,
    String? targetMuscleGroupId,
    String? difficultyLevelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyRecommendationExercise, [
              limit,
              targetMuscleGroupId,
              difficultyLevelId,
            ]),
            returnValue:
                _i3.Future<_i4.ApiResult<List<_i5.ExerciseEntity>>>.value(
                  _i6.dummyValue<_i4.ApiResult<List<_i5.ExerciseEntity>>>(
                    this,
                    Invocation.method(#getDailyRecommendationExercise, [
                      limit,
                      targetMuscleGroupId,
                      difficultyLevelId,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<List<_i5.ExerciseEntity>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i7.MealEntity>>> getFoodRecommendation() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodRecommendation, []),
            returnValue: _i3.Future<_i4.ApiResult<List<_i7.MealEntity>>>.value(
              _i6.dummyValue<_i4.ApiResult<List<_i7.MealEntity>>>(
                this,
                Invocation.method(#getFoodRecommendation, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<List<_i7.MealEntity>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i8.MuscleGroupEntity>?>> getAllMuscles() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMuscles, []),
            returnValue:
                _i3.Future<_i4.ApiResult<List<_i8.MuscleGroupEntity>?>>.value(
                  _i6.dummyValue<_i4.ApiResult<List<_i8.MuscleGroupEntity>?>>(
                    this,
                    Invocation.method(#getAllMuscles, []),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<List<_i8.MuscleGroupEntity>?>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i9.MuscleEntity>?>> getMusclesByGroup(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMusclesByGroup, [id]),
            returnValue:
                _i3.Future<_i4.ApiResult<List<_i9.MuscleEntity>?>>.value(
                  _i6.dummyValue<_i4.ApiResult<List<_i9.MuscleEntity>?>>(
                    this,
                    Invocation.method(#getMusclesByGroup, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<List<_i9.MuscleEntity>?>>);
}
