// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/auth/data/datasources/impl/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:fitness_app/core/api_layer/api_client/api_client.dart' as _i9;
import 'package:fitness_app/core/api_layer/models/requests/login_request_dto.dart'
    as _i17;
import 'package:fitness_app/core/api_layer/models/responses/login_response_dto.dart'
    as _i16;
import 'package:fitness_app/core/api_layer/models/responses/muscles_response.dart'
    as _i8;
import 'package:fitness_app/core/api_layer/models/responses/workout_response.dart'
    as _i7;
import 'package:fitness_app/features/auth/data/models/forget_password/request/forget_password_request_dto.dart'
    as _i13;
import 'package:fitness_app/features/auth/data/models/forget_password/response/forget_password_response_dto.dart'
    as _i3;
import 'package:fitness_app/features/auth/data/models/otp_verification/request/otp_verification_request_dto.dart'
    as _i14;
import 'package:fitness_app/features/auth/data/models/otp_verification/response/otp_verification_response_dto.dart'
    as _i4;
import 'package:fitness_app/features/auth/data/models/register/request/register_request_dto.dart'
    as _i12;
import 'package:fitness_app/features/auth/data/models/register/response/register_response_dto.dart'
    as _i2;
import 'package:fitness_app/features/auth/data/models/reset_password/request/reset_password_request_dto.dart'
    as _i15;
import 'package:fitness_app/features/auth/data/models/reset_password/response/reset_password_response_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:retrofit/retrofit.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponseDto_0 extends _i1.SmartFake
    implements _i2.RegisterResponseDto {
  _FakeRegisterResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseDto_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOtpVerificationResponseDto_2 extends _i1.SmartFake
    implements _i4.OtpVerificationResponseDto {
  _FakeOtpVerificationResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_4<T> extends _i1.SmartFake
    implements _i6.HttpResponse<T> {
  _FakeHttpResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutResponse_5 extends _i1.SmartFake
    implements _i7.WorkoutResponse {
  _FakeWorkoutResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMusclesResponse_6 extends _i1.SmartFake
    implements _i8.MusclesResponse {
  _FakeMusclesResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i9.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String> getSampleData() =>
      (super.noSuchMethod(
            Invocation.method(#getSampleData, []),
            returnValue: _i10.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#getSampleData, []),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<_i2.RegisterResponseDto> register(
    _i12.RegisterRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i10.Future<_i2.RegisterResponseDto>.value(
              _FakeRegisterResponseDto_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i10.Future<_i2.RegisterResponseDto>);

  @override
  _i10.Future<_i3.ForgetPasswordResponseDto> forgetPassword(
    _i13.ForgetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [request]),
            returnValue: _i10.Future<_i3.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_1(
                this,
                Invocation.method(#forgetPassword, [request]),
              ),
            ),
          )
          as _i10.Future<_i3.ForgetPasswordResponseDto>);

  @override
  _i10.Future<_i4.OtpVerificationResponseDto> verifyOtp(
    _i14.OtpVerificationRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [request]),
            returnValue: _i10.Future<_i4.OtpVerificationResponseDto>.value(
              _FakeOtpVerificationResponseDto_2(
                this,
                Invocation.method(#verifyOtp, [request]),
              ),
            ),
          )
          as _i10.Future<_i4.OtpVerificationResponseDto>);

  @override
  _i10.Future<_i5.ResetPasswordResponseDto> resetPassword(
    _i15.ResetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i10.Future<_i5.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_3(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i10.Future<_i5.ResetPasswordResponseDto>);

  @override
  _i10.Future<_i6.HttpResponse<_i16.LoginResponseDto>> login({
    required _i17.LoginRequestDto? loginRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#loginRequestDto: loginRequestDto}),
            returnValue:
                _i10.Future<_i6.HttpResponse<_i16.LoginResponseDto>>.value(
                  _FakeHttpResponse_4<_i16.LoginResponseDto>(
                    this,
                    Invocation.method(#login, [], {
                      #loginRequestDto: loginRequestDto,
                    }),
                  ),
                ),
          )
          as _i10.Future<_i6.HttpResponse<_i16.LoginResponseDto>>);

  @override
  _i10.Future<_i7.WorkoutResponse> getWorkOuts() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkOuts, []),
            returnValue: _i10.Future<_i7.WorkoutResponse>.value(
              _FakeWorkoutResponse_5(this, Invocation.method(#getWorkOuts, [])),
            ),
          )
          as _i10.Future<_i7.WorkoutResponse>);

  @override
  _i10.Future<_i8.MusclesResponse> getMuscleGroup(String? muscleGroupId) =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleGroup, [muscleGroupId]),
            returnValue: _i10.Future<_i8.MusclesResponse>.value(
              _FakeMusclesResponse_6(
                this,
                Invocation.method(#getMuscleGroup, [muscleGroupId]),
              ),
            ),
          )
          as _i10.Future<_i8.MusclesResponse>);
}
